steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - "-c"
      - |
        echo $'\n  APP_KEY: '$_APP_KEY >> app.yaml
        gcloud config set app/cloud_build_timeout 3600 && gcloud app deploy app.yaml -q --promote -v=$BUILD_ID --project=$PROJECT_ID --no-cache
    entrypoint: bash
